import type { Metadata } from "next";
import Sideber from "./Sideber";



export const metadata: Metadata = {
  title: "Luxe Bloom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
    
     <div className="flex gap-4 pt-10 " >
        <div>
            <Sideber/>
        </div>
        {children}
     </div>
  
  );
}
