import type { Metadata } from "next";
import Footer from "@/components/Sections/Footer";
import { Navbar } from "@/components/navbar/header-navbar";
// import { PromotionalCarousel } from "@/components/Sections/PromotionalCarousel";



export const metadata: Metadata = {
  title: "Luxe Bloom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {/* <PromotionalCarousel /> */}
        <Navbar/>
        <div className="mt-20">
        {children}
        </div>
          <Footer/>
      </body>
    </html>
  );
}
